[package]
name = "colored-macro-impl"
edition = "2021"
version = "0.0.0+UNVERSIONED"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
css-color = "0.2"
proc-macro2.workspace = true
quote = "1.0"
syn.workspace = true
